<a href="https://colab.research.google.com/github/nitish36200/Projects/blob/main/ml_project1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#importing all required libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.graph_objects as go

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split


from itertools import product
from collections import Counter
from sklearn.cluster import k_means
from sklearn.preprocessing import LabelEncoder

In [ ]:
train = pd.read_csv("sales_train.csv",parse_dates=['date'])

In [ ]:
test= pd.read_csv("test.csv")

In [ ]:
shop= pd.read_csv("shops.csv")

In [ ]:
items = pd.read_csv("items.csv")

In [ ]:
item_categories= pd.read_csv("item_categories.csv")

In [ ]:
train.head()

         date  date_block_num  shop_id  item_id  item_price  item_cnt_day
0  02.01.2013               0       59    22154      999.00           1.0
1  03.01.2013               0       25     2552      899.00           1.0
2  05.01.2013               0       25     2552      899.00          -1.0
3  06.01.2013               0       25     2554     1709.05           1.0
4  15.01.2013               0       25     2555     1099.00           1.0

In [ ]:
test.head()

   ID  shop_id  item_id
0   0        5     5037
1   1        5     5320
2   2        5     5233
3   3        5     5232
4   4        5     5268

In [ ]:
shop.head()

                        shop_name  shop_id
0   !Якутск Орджоникидзе, 56 фран        0
1   !Якутск ТЦ "Центральный" фран        1
2                Адыгея ТЦ "Мега"        2
3  Балашиха ТРК "Октябрь-Киномир"        3
4        Волжский ТЦ "Волга Молл"        4

In [ ]:
items.head()

                                           item_name  item_id  item_category_id
0          ! ВО ВЛАСТИ НАВАЖДЕНИЯ (ПЛАСТ.)         D        0                40
1  !ABBYY FineReader 12 Professional Edition Full...        1                76
2      ***В ЛУЧАХ СЛАВЫ   (UNV)                    D        2                40
3    ***ГОЛУБАЯ ВОЛНА  (Univ)                      D        3                40
4        ***КОРОБКА (СТЕКЛО)                       D        4                40

In [ ]:
item_categories.head()

        item_category_name  item_category_id
0  PC - Гарнитуры/Наушники                 0
1         Аксессуары - PS2                 1
2         Аксессуары - PS3                 2
3         Аксессуары - PS4                 3
4         Аксессуары - PSP                 4

Exploring the Data

In [ ]:
print("No. of shops: ", len(shop))
print("No. ofnumber of categories:", len(item_categories))
print("No. of items:", len(items))
print("No. of train:",len(train))
print("No. of test:", len(test))

No. of shops:  60
No. ofnumber of categories: 84
No. of items: 22170
No. of train: 1708162
No. of test: 214200

In [ ]:
shop.nunique()

shop_name    60
shop_id      60
dtype: int64

In [ ]:
items.nunique()

item_name           22170
item_id             22170
item_category_id       84
dtype: int64

In [ ]:
item_categories.nunique()

item_category_name    84
item_category_id      84
dtype: int64

In [ ]:
train.describe()

       date_block_num       shop_id       item_id    item_price  item_cnt_day
count    1.708162e+06  1.708162e+06  1.708162e+06  1.708162e+06  1.708162e+06
mean     7.681328e+00  3.282783e+01  1.015052e+04  7.633236e+02  1.230285e+00
std      4.846516e+00  1.630251e+01  6.332143e+03  1.420611e+03  1.765098e+00
min      0.000000e+00  0.000000e+00  1.000000e+00 -1.000000e+00 -2.200000e+01
25%      3.000000e+00  2.200000e+01  4.380000e+03  2.053700e+02  1.000000e+00
50%      8.000000e+00  3.100000e+01  9.151000e+03  3.990000e+02  1.000000e+00
75%      1.200000e+01  4.700000e+01  1.558500e+04  7.990000e+02  1.000000e+00
max      1.700000e+01  5.900000e+01  2.216900e+04  3.079800e+05  5.020000e+02

In [ ]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1708162 entries, 0 to 1708161
Data columns (total 6 columns):
 #   Column          Dtype
---  ------          -----
 0   date            object
 1   date_block_num  int64
 2   shop_id         int64
 3   item_id         int64
 4   item_price      float64
 5   item_cnt_day    float64
dtypes: float64(2), int64(3), object(1)
memory usage: 78.2+ MB

In [ ]:
#Missing Values
train.isnull().sum()

date              0
date_block_num    0
shop_id           0
item_id           0
item_price        0
item_cnt_day      0
dtype: int64